### PR TITLE
Add AsyncParsableCommand to README

### PR DESCRIPTION
**Pull request by robertmryan**
Update to README and markdown documentation to include easily discovered references to `AsyncParsableCommand`.

In issue https://github.com/apple/swift-argument-parser/issues/561, I noted that `AsyncParsableCommand` was not easily discovered. This pull request attempts to remedy this by adding simple references to it in `README.md`, `ArgumentParser.md`, and `Validation.md`. In `GettingStarted.md` I went so far as to add a new section with an example.

Please note, this only includes documentation changes and does not include any code changes. Therefore, there are no tests for this PR.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by rismay** [comment]
This is really hard to discover without documentation. Please merge if possible.

**Comment by robertmryan** [comment]
FWIW, the status checks said it was out of date, so I went back to my fork and updated it (while preserving my changes). I hope this helps…

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
