### PR TITLE
Add localisation support for messages

### PR DESCRIPTION
**Pull request by bitigchi**
See #203.

This PR adds support for localising Swift Argument Parser. First contribution, please mention any mistakes/possible improvements.

- [x] Modify strings for `NSLocalizedString`
- [x] Have Swift 5.3 recognise `.lproj` files in bundle

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
@bitigchi Thanks for your work on this! Just a note that I'm still evaluating whether it's okay to move up to requiring 5.3 for the package at this time.

Also, do you have ideas about testing?

**Comment by bitigchi** [comment]
> @bitigchi Thanks for your work on this! Just a note that I'm still evaluating whether it's okay to move up to requiring 5.3 for the package at this time.
> 
> Also, do you have ideas about testing?

I will add tests, but I am hesitant to proceed in general without confirming why Swift 5.3 does not automatically parse `.lproj` folders in CLI apps. Is this a bug?

**Comment by bitigchi** [comment]
Update:
- Localisations work, I can confirm it via failing tests with my system locale set in Turkish.
- I am in the process of adding my own tests, but they seem to pass no matter what.
  - I added Resources and .lproj folders under the tests folder, and localised a simple `AssertHelp`, but it's passing even if the localisations are not accurate.
- I added a simple `uppercase(with: Locale)` to have more accurate uppercasing according to the locale, but this time it fails tests with the words `OPTIONS` in it (tries to capitalise i as İ, even if I set my system to English. I added an `if` check to `HelpGenerator.swift` to use `uppercased()` for English locale, but doesn't seem to mind. Any ideas on how to proceed?

**Comment by bitigchi** [comment]
Awaiting reviews. Thanks in advance.

**Comment by bitigchi** [comment]
@swift-ci Please test

**Comment by bitigchi** [comment]
@shahmishal, reason for closing?

**Comment by shahmishal** [comment]
We deleted `master` branch, and all development needs to be done on `main` branch

**Pull request closed without merging**
