### PR TITLE
fix: 🐛 Declare `GenerateManualPlugin` as plugin product

### PR DESCRIPTION
**Pull request by MarcoEidinger**
✅ Closes: #455

`ArgumentParser` 1.1.3 includes a SwiftPM plugin for generating man pages. However, this plugin is not visible to packages that declare `ArgumentParser` as a package dependency.

Defining a product of type `plugin` in the package manifest will solve that. Running `swift package plugin --list` for a package, that declares `ArgumentParser` as a package dependency, will then list the `GenerateManualPlugin`

```
‘experimental-generate-manual’ (plugin ‘GenerateManualPlugin’ in package ‘swift-argument-parser’)
```

### Checklist
- [ ] I've added at least one test that validates that my change is working, if appropriate
- [X] I've followed the code style of the rest of the project
- [X] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary

### CODE REVIEW

**Review by rauhul — APPROVED** [review]
Thanks

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by MarcoEidinger** [comment]
Is this PR good to be merged or do you need anything else?

**Comment by rauhul** [comment]
Yeah it looks good to me but I'd like @natecook1000 to sign off first.

**Comment by MarcoEidinger** [comment]
Hi @natecook1000, this PR provides the fix for generating man pages from the consumer's package root. Would love to see this getting merged soon :)

**Comment by rauhul** [comment]
I believe Nate will be able to approve this in the upcoming week; sorry about the wait.

**Comment by rauhul** [comment]
Spoke to Nate offline and this looks good. Thanks for your patience!

**Comment by MarcoEidinger** [comment]
Awesome! What is the ETA for a new release (1.1.4) that will include the fix? After all, the feature to generate man pages is otherwise only working for people pinning to the main branch.

**Comment by rauhul** [comment]
1.1.4 has been released with this fix.

**Pull request merged**
