### PR TITLE
Support Exit codes from thrown CustomNSError conformers

### PR DESCRIPTION
**Pull request by SergeyPetrachkov**
Introduce support for CustomNSError protocol conformers. Previously executable targets would exit with code 1, but it seems like a good idea to exit with a code provided by the user's custom error type.

I've added a sample executable target, and a few tests to cover things up.

This PR references https://github.com/apple/swift-argument-parser/issues/243 and https://github.com/apple/swift-argument-parser/issues/230

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary(no need i guess)

### CODE REVIEW

**Comment by SergeyPetrachkov** [comment]
@swift-ci please test

**Comment by natecook1000** [comment]
Thanks for this contribution, @SergeyPetrachkov! I think we can test this without adding the separately compiled example — can you add your tests for handling `CustomNSError` types to [ExitCodeTests.swift](https://github.com/apple/swift-argument-parser/blob/main/Tests/ArgumentParserUnitTests/ExitCodeTests.swift)?

**Comment by SergeyPetrachkov** [comment]
> Thanks for this contribution, @SergeyPetrachkov! I think we can test this without adding the separately compiled example — can you add your tests for handling `CustomNSError` types to [ExitCodeTests.swift](https://github.com/apple/swift-argument-parser/blob/main/Tests/ArgumentParserUnitTests/ExitCodeTests.swift)?

Yes, sure, I'll do this

**Comment by SergeyPetrachkov** [comment]
@natecook1000 I've updated the PR according to your notes. Take a look when you have time.

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
