### PR TITLE
Add support for Apple Silicon in SwiftSupport.cmake

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This matches the behavior of [a similar `elseif` branch in the Swift toolchain itself](https://github.com/apple/swift/blob/b80e4bf8f866be26a4108bd92f97b2a182662642/CMakeLists.txt#L594).

### Checklist
- [ ] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
I wonder if I can't build on CI because I don't have commit access here? 🤔

**Comment by mpapple-swift** [comment]
> I wonder if I can't build on CI because I don't have commit access here? 🤔

I can't speak to whether you need commit privileges, but the macOS build failed saying it couldn't clone the repo.  Note the Linux build passed.

**Comment by MaxDesiatov** [comment]
Huh, I think I saw the same error for the Linux build on the first try. Let's hope it's intermittent...

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@MaxDesiatov Thanks for this! Were you able to test on an Apple Silicon Mac?

**Comment by MaxDesiatov** [comment]
Do you mean running the test suite via CMake on Apple Silicon, or just plain building the project? I was able to do the latter on Apple Silicon as a part of a bigger toolchain build, only with this patch applied (which enables the build).

**Comment by natecook1000** [comment]
I think that's sufficient for me to merge, thanks!

**Pull request merged**
