### PR TITLE
Prefer if-let shorthand in `CountLines.swift`

### PR DESCRIPTION
**Pull request by KS1019**
`CountLines.swift` uses the mix of the normal if-let and the shorthand. This PR changes the normal version to the shorthand to stay consistent.

### Checklist
- N/A I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- N/A I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
Looks good to me, now that we're on 5.7 as the minimum Swift version. Thanks, @KS1019!

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by rauhul** [comment]
We can merge this, but I personally really dislike this syntax because it doesn't work with property chaining. This becomes a deal breaker for me because explicit `self` is a _must_ imo.

**Comment by rauhul** [comment]
@swift-ci test

**Pull request merged**
