### PR TITLE
Default to single page manuals

### PR DESCRIPTION
**Pull request by rauhul**
- Changes the generate-manual --single-page argument to --multi-page, so
  generate-manual will create a single manual page with all subcommand
  information by default instead of many distinct files.

### CODE REVIEW

**Comment by rauhul** [comment]
@swift-ci please test

**Review by natecook1000 — APPROVED** [review]
Looks good! Definitely seems like a better default.

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
@swift-ci please test

**Pull request merged**
