### PR TITLE
build: repair the build after #404

### PR DESCRIPTION
**Pull request by compnerd**
This fixes the build with CMake after #404.

Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.

### Checklist
- [ ] I've added at least one test that validates that my change is working, if appropriate
- [ ] I've followed the code style of the rest of the project
- [ ] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @natecook1000

**Comment by natecook1000** [comment]
Thanks, @compnerd ❤️

**Comment by compnerd** [comment]
Ugh, I missed the `@main` usage ... :sigh: I'll have a fix for that shortly.

**Pull request merged**
