### PR TITLE
Generate useful synopsis for commands with many options

### PR DESCRIPTION
**Pull request by lorentey**
ArgumentParser is configured not to emit detailed synopsis when it would contain more than a dozen entries. This makes sense; however, eliding all information makes the synopsis rather useless.

While commands may have dozens of options, in most cases, only a few of them are required — so we can keep the synopsis short but still useful by only displaying the required parts.

### Checklist
- [X] I've added at least one test that validates that my change is working, if appropriate
- [X] I've followed the code style of the rest of the project
- [X] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [X] I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
This is such a great improvement — thanks @lorentey! 🎉

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by lorentey** [comment]
```
swift-argument-parser/Tests/ArgumentParserPackageManagerTests/HelpTests.swift:113: error: HelpTests.testGetMirrorHelp : XCTAssertEqual failed: ("USAGE: package config get-mirror [<options>] --package-url <package-url>
```

D'oh. I must have not run all tests.

One additional improvement would be to include optional positional arguments in the shortened synopsis. This acknowledges the special nature of positional arguments, and it is the convention adopted by most modern command line interfaces that use synopsis shortening:

```
rsync [OPTION]... [USER@]HOST:SRC [DEST]
patch [OPTION]... [ORIGFILE [PATCHFILE]]
fish [OPTIONS] [-c command] [FILE [ARGUMENTS...]]
rg [OPTIONS] PATTERN [PATH ...]
fd [FLAGS/OPTIONS] [<pattern>] [<path>...]
usage: /usr/local/bin/python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
```

AFAICT, the synopsis is the only place where the optionality/multiplicity of positional arguments is explained in the help message, so it seems important to preserve it.

**Comment by natecook1000** [comment]
That also sounds like a good improvement! 🥇

**Comment by lorentey** [comment]
@swift-ci test

**Comment by natecook1000** [comment]
Looks great! 🎉

**Pull request merged**
