### PR TITLE
Remove LinuxMain.swift

### PR DESCRIPTION
**Pull request by keith**
Swift 5.5+ Swift Package Manager warns that `--enable-test-discovery` is
enabled by default. I assume for this project that should mean this
isn't needed anymore on `main`.

### CODE REVIEW

**Comment by keith** [comment]
@natecook1000 can you review?

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by keith** [comment]
@swift-ci Please test

**Comment by keith** [comment]
the main branch bumped the tools version to 5.5, so that change is no longer needed here

**Comment by keith** [comment]
@natecook1000 could you review 🙏🏻

**Review by natecook1000 — APPROVED** [review]
LGTM! Thanks, @keith!

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by keith** [comment]
All green! (I don't have access to merge on this one)

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
