### PR TITLE
Backport CMake support to 3.15.1

### PR DESCRIPTION
**Pull request by owenv**
Some of the SPM builders appear to be running CMake 3.15.4, so I'm back porting ArgumentParser to 3.15.1 to match SPM's minimum version. I haven't tested this on Windows yet to make sure the output directory workarounds behave as expected, I'm going to try to spin up a VM this weekend.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

cc @compnerd

### CODE REVIEW

**Comment by compnerd** [comment]
Sure, that’s reasonable.  From the CMake perspective, it seems fine.  Just adds a bit of complexity, so as long as Nate’s happy, LGTM.

**Comment by natecook1000** [comment]
@owenv Looks good on my end, just let me know when you’ve been able to verify on Windows. Thanks! 🙏

**Comment by compnerd** [comment]
@natecook1000 https://dev.azure.com/compnerd/swift-build/_build/results?buildId=33747&view=results

Lets just make it easy - triggered a CI run for argument-parser :)

**Comment by compnerd** [comment]
Seems to build fine on Windows :)

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
