### PR TITLE
Fix small typo in `CommandConfiguration` documentation

### PR DESCRIPTION
**Pull request by CypherPoet**
# Checklist
- [ ] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
@CypherPoet Thanks for this fix! Would you mind clearing out the whitespace-only changes?

**Comment by CypherPoet** [comment]
@natecook1000 Sorry about that 😄. Updated and rebased.

**Comment by natecook1000** [comment]
A+++ 🎉

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
