### PR TITLE
Fixed custom completion not working in zsh when command name contains a dash

### PR DESCRIPTION
**Pull request by CraigSiemens**
### Related issues and PRs

- #277 
- #284 

### Description
This adds onto the fix from #284 that added support for commands with dashes in the name. 

When getting completions for an argument using `CompletionKind.custom(...)` an error occurs. #284 updated [a variable](https://github.com/apple/swift-argument-parser/pull/284/files#diff-b243e9c8a946a341ab514c2d5ce1b9f27a3bb6cf672b14ab02f0d221a491d645R20) but missed updating where that variable is used to also escape the command name.

This updates the usage of that variable to also escape the command name and updates the tests to check for it.

### Example
If I have a command called `cli-tools` with an argument that has a `CompletionKind.custom(...)`, typing `cli-tools a` then pressing tab will produce the following error.

```
cli-tools a_custom_completion:1: command not found: -tools_commandname
_custom_completion:1: command not found: -tools_commandname
  cli-tools a
```

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
Thanks for this fix, @CraigSiemens!

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by CraigSiemens** [comment]
@natecook1000 Is there's anything on my side that's holding this up from being merged? I'm just curious since this PR's been open for over a month.

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@CraigSiemens Nothing on your end! Merging once green 👍🏻

**Pull request merged**
