### PR TITLE
Fix various broken links in documentation articles.

### PR DESCRIPTION
**Pull request by ianacl**
Fixed various links in documentation articles that were broken by file name changes.
Manually validated change - test checklist item is not applicable. 

### Checklist
- [ ] ~I've added at least one test that validates that my change is working, if appropriate~
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by atierian** [comment]
Just checking in to see if there's anything I can do to help the review process along.
Thanks!

**Comment by natecook1000** [comment]
Thanks for these fixes, @atierian! Could you update your changes to the latest `main` so this can be merged?

**Comment by atierian** [comment]
Updated. Thanks @natecook1000.

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
