### PR TITLE
Support passing arguments to async main

### PR DESCRIPTION
**Pull request by Austinpayne**
Adds a new static main function to `AsyncParsableCommand` to allow users to manually pass in arguments. The new functions behaves identically to the version found in `ParsableCommand` (see: https://github.com/apple/swift-argument-parser/blob/main/Sources/ArgumentParser/Parsable%20Types/ParsableCommand.swift#L126). This functionality is useful for manually building an argument list, e.g. when building a busybox~like binary.

### Checklist
- [ ] I've added at least one test that validates that my change is working, if appropriate
- [X] I've followed the code style of the rest of the project
- [X] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
Thanks, @Austinpayne! This is a great addition — when I saw it I thought, "don't we have that already?"

Would you mind adding a test that verifies that this will parse and run an async command correctly? Thank you!

**Review by blochberger — APPROVED** [review]

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
