### PR TITLE
[NFC] Improving edit distance string extension

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Improving implementation of edit distance string extension by:
* Using only two arrays `n + 1` instead of an `m x n` matrix.
* Trimming common prefix and suffix as an optimization for reducing size/complexity 
* Tests for those cases were added.

Been playing around with ways to improve it more in https://github.com/LucianoPAlmeida/strings

**Benchmarks**
**Code:**
```swift
var benchmark = Benchmark(title: "Edit distance")
let inputGeneratorCommon: (Int) -> (String, String) = { size in
    let common = String(repeating: "a", count: size / 4)
    let s1 = String(repeating: "foo", count: (size / 2) / 3)
    let s2 = String(repeating: "bar", count: (size / 2) / 3)
    return (common + s1 + common, common + s2 + common)
}

let inputGeneratorDifferent: (Int) -> (String, String) = { size in
  let s1 = String(repeating: "foo", count: size)
  let s2 = String(repeating: "bar", count: size)
  return (s1, s2)
}

benchmark.registerInputGenerator(inputGeneratorCommon)
benchmark.add(
  title: "Opt editDistance common prefix/suffix",
  input: (String, String).self,
  maxSize: 1000
) { input in
  return { timer in
    let d = input.0.editDistance(to: input.1)
    blackHole(d)
  }
}

benchmark.add(
  title: "editDistance common prefix/suffix",
  input: (String, String).self,
  maxSize: 1000
) { input in
  return { timer in
    let d = input.0.editDistanceOld(to: input.1)
    blackHole(d)
  }
}

benchmark.registerInputGenerator(inputGeneratorDifferent)
benchmark.add(
  title: "Opt editDistance",
  input: (String, String).self,
  maxSize: 1000
) { input in
  return { timer in
    let d = input.0.editDistance(to: input.1)
    blackHole(d)
  }
}

benchmark.add(
  title: "editDistance",
  input: (String, String).self,
  maxSize: 1000
) { input in
  return { timer in
    let d = input.0.editDistanceOld(to: input.1)
    blackHole(d)
  }
}
```
chart

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [ ] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
cc @natecook1000

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
