### PR TITLE
Change name of plugin target to readable form

### PR DESCRIPTION
**Pull request by clayellis**
This PR updates the name of the "Generate Manual" plugin so that it appears in a more readable "command" form in the context menu in Xcode.

Before:
image

After:
image

### Checklist
- [ ] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by clayellis** [comment]
Arguably, there should be an additional parameter on the `Plugin` target type that allows for an easier "external" name configuration without having to rename actual targets. Maybe it's worth a pitch? Someone else may have to take it up, though.

**Comment by rauhul** [comment]
I'm on board with making the name look better in Xcode, though I'm not a huge fan of having a space in the file path.

@neonichu do you have any thoughts, is this the best solution for improving the display name in Xcode?

**Comment by clayellis** [comment]
> I'm on board with making the name look better in Xcode, though I'm not a huge fan of having a space in the file path.

This _avoids_ having a space in the file path (by explicitly declaring a `path`) and moves that to the target name.

**Review by natecook1000 — APPROVED** [review]
Since this keeps the command-line verb the same, it looks like the change is really kept local to the package manifest, which then gets picked up by Xcode for the action name. Given that, I think this is fine to merge, especially since it doesn't bind us with source compatibility or anything else if we do discover problems down the road.

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by clayellis** [comment]
Thanks for merging this! I hope to contribute in larger ways in the future!

**Pull request merged**
