### PR TITLE
Changing the access level of `ValidationError.message`

### PR DESCRIPTION
**Pull request by rjstelling**
This is a very short PR that came out of some changes made in #115. Because it is an API change is was suggested this become a PR in its own right.

However, looking at the code I wanted to make sure the motivations are correct and consider some alternatives. 

### Do we need this change?
`ValidationError` conforms to `CustomStringConvertible`, `description` is `public` and it vends `message`. So client code can read the `message` value without this change.

### Alternative 1
Remove `message` value entirely and use `description`.

```swift
public struct ValidationError: Error, CustomStringConvertible {
  public internal(set) var description: String
  
  /// Creates a new validation error with the given message.
  public init(_ message: String) {
    self.description = message
  }
}
```

### Alternative 2
`message` should be `private(set)`. No library code (currently) changes the `message` string, and its internal by default.

```swift
public struct ValidationError: Error, CustomStringConvertible {
  public private(set) var message: String
  
  /// Creates a new validation error with the given message.
  public init(_ message: String) {
    self.message = message
  }
  
  public var description: String {
    message
  }
}
```

### Alternative 3

If we are making `message` `private` these is no need for it to be a `var`, so change it to a public `let`.

```swift
public struct ValidationError: Error, CustomStringConvertible {
  public let message: String
  
  /// Creates a new validation error with the given message.
  public init(_ message: String) {
    self.message = message
  }
  
  public var description: String {
    message
  }
}
```

### Checklist
- [x] I've updated the documentation if necessary
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- ~~I've added at least one test that validates that my change is working, if appropriate~~

### CODE REVIEW

**Comment by natecook1000** [comment]
This looks great, @rjstelling. If you can add a doc string to the property we'll get this merged!

**Comment by rjstelling** [comment]
> This looks great, @rjstelling. If you can add a doc string to the property we'll get this merged!

Out of curiosity (and if you have the time), I'd love to know why you didn't like any of the alternatives. Left to my own devices I think I would have chosen 3.

**Comment by natecook1000** [comment]
> Out of curiosity (and if you have the time), I'd love to know why you didn't like any of the alternatives. Left to my own devices I think I would have chosen 3.

I actually go the other way, and prefer `var` for struct properties that don't have any kind of preconditioning interdependencies on other properties. IME their mutability is better handled at the instance level, and limiting that may just make more work for people.

The change here is a step in that direction, but I think it'd also be fine to just make it a `public var`.

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
