### PR TITLE
Don't show Optional(x) when displaying default values in help.

### LINKED ISSUE #26: Default Option value in help text includes `Optional(…)`
the following option

```swift
@Option(default: true)
var doStuff: Bool?
```

would result in the following default value description:

```
(default: Optional(true))
```

This is counterintuitive and requires user to workaround it.

### PR DESCRIPTION
**Pull request by sjavora**
Fixes #26

### CODE REVIEW

**Comment by sjavora** [comment]
@natecook1000 could you please take a look?

**Comment by natecook1000** [comment]
I've been thinking about the right approach to #26, since it's not actually a configuration that we want people to use. If you provide a non-`nil` default value, the property will never be `nil`, so it really shouldn't be optional in the first place. We may actually need to drop `ExpressibleByArgument` conformance from `Optional` and add an initializer specifically for optional values. 

In any case, it would be great to fix this, but I don't want to add public API to do so. Can you look for a solution that could be handled internally to the library?

**Comment by sjavora** [comment]
I've removed the protocol requirement – the implementation now uses `Mirror` to determine whether the type is optional. I'm not thrilled about it, but didn't come up with anything better.

**Comment by sjavora** [comment]
@natecook1000 fixed conflicts - please let me know if this approach is OK from your POV 🙂

**Comment by natecook1000** [comment]
Let's do this!

**Pull request merged**
