### PR TITLE
Clean up help generation

### PR DESCRIPTION
**Pull request by rauhul**
- Adds check to ensure that `wrapped(to:wrappingIndent:)` doesn't
  attempt to retrieve a negative prefix.
- The Usage struct was composed of an array of strings which always
  contained exact one string at runtime. This struct has been removed
  and replaced with a single usage string.
- Removes HelpGenerator._screenWidthOverride in favor of explicitly
  setting the screen width in generateHelp calls.

### CODE REVIEW

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
💻👍🏻

**Pull request merged**
