### PR TITLE
Update changelog for 1.2.3 release

### PR DESCRIPTION
**Pull request by rauhul**

### CODE REVIEW

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
@compnerd gonna try to merge/tag this today (I'm OOO tomorrow and Nate is currently OOO)

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
@compnerd any idea why CI isn't triggering?

**Comment by compnerd** [comment]
Not sure .. @shahmishal?

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
I wonder if `release/` is reserved...

**Comment by rauhul** [comment]
There we go... Weird...

**Comment by rauhul** [comment]
@compnerd merged and tagged!

**Pull request merged**
