### PR TITLE
Add SwiftWasm (WebAssembly) support

### PR DESCRIPTION
**Pull request by yonihemi**
Adds support for building WebAssembly binaries targeting [WASI](https://wasi.dev/) using [SwiftWasm](https://swiftwasm.org/) toolchains.

### Minor variations
- `EX_USAGE` is not exposed by WASI so a generic exit code of 1 is returned for validation failures.
- Terminal size is not supported so a default is returned.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
	- Running compiled SwiftWasm binary requires an external runtime. I've added a sample project with binary and instructions in [another repo](https://github.com/yonihemi/use-argument-parser/).
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary
	- N/A

### CODE REVIEW

**Comment by yonihemi** [comment]
@natecook1000 @rauhul as we've officially released the SwiftWasm 5.5 toolchain I've updated the [sample project](https://github.com/yonihemi/use-argument-parser/) and build instructions. I hope you get a chance to review these changes.

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
@natecook1000 this looks fine to me, though I wish swift-ci was setup to test for windows & wasi

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
LGTM! Thanks for including that test project / instructions, @yonihemi :shipit:

**Comment by yonihemi** [comment]
Thank you!

**Pull request merged**
