### PR TITLE
Add support for Musl libc

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Since Musl is sufficiently different from Glibc (see https://wiki.musl-libc.org/functional-differences-from-glibc.html), it requires a different import, which now should be applied to files that have `import Glibc` in them.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
macOS failure is unrelated and is also reproduced in an empty PR https://github.com/apple/swift-argument-parser/pull/575. @rauhul have you seen this one before?

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
