### PR TITLE
Fix the defaultValueDescription for string enums whose values differ from the case names

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
defaultValueDescription is always the enum case name, but that's not a valid argument when the enum value differs from the case name. Extend ExpressibleByArgument to use rawValue for defaultValueDescription for string enums.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Review by rauhul — APPROVED** [review]
LGTM thanks for adding tests too! Probably should wait for Nate's eyes too before merging.

**Comment by rauhul** [comment]
@swift-ci please test

**Review by natecook1000 — APPROVED** [review]
LGTM! Thanks, @ian-twilightcoder 👏🏻

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by rauhul** [comment]
@swift-ci please test

**Pull request merged**
