### PR TITLE
Fixing math example on Linux

### PR DESCRIPTION
**Pull request by BradLarson**
The usage of `sqrt()` requires linking libm on Linux. This adds the appropriate CMake entry to allow for this.

### Checklist
- [X] I've added at least one test that validates that my change is working, if appropriate
- [X] I've followed the code style of the rest of the project
- [X] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [X] I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@BradLarson Thanks for these fixes! I’ll work on getting a CMake build added as part of the CI.

**Comment by BradLarson** [comment]
The one to thank for these is actually @compnerd. He walked me through the fixes as part of related work on [a separate PR](https://github.com/tensorflow/swift-models/pull/565) that I was encountering CMake issues with.

We've been using ArgumentParser in other existing targets there, but I realized none were set up for CMake yet. This was the first.

**Pull request merged**
