### PR TITLE
[GSoC] Conversation for required @Argument 2

### PR DESCRIPTION
**Pull request by KeithBird**
Solution to the issue #453.

This PR is used to track progress and view differences to make discussions easier.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](https://github.com/apple/swift-argument-parser/blob/main/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by KeithBird** [comment]
Recommit #454

**Review by natecook1000 — APPROVED** [review]
LGTM!

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by KeithBird** [comment]
> @swift-ci Please test

Interactive mode is enabled by default, which causes some previous tests to check for error messages to fail.

**Comment by natecook1000** [comment]
Eventually the querying UI should only be enabled when in an interactive shell. Let's merge this for now and address that soon.

**Pull request merged**
