### PR TITLE
Add customization point for command usage text

### PR DESCRIPTION
**Pull request by natecook1000**
### Description
This adds a `usage` property to `CommandConfiguration` that lets tool authors customize their command's usage string.

### Detailed Design

The `CommandConfiguration` type now has a `usage` property that defaults to a `nil` string. When non-`nil`, this string is used instead of the auto-generated usage string.

### Documentation Plan

Symbol documentation is included, but the Help article should be updated to show this additional API.

### Test Plan
Unit tests cover the new feature.

### Source Impact
This is an additive change, and requires a new initializer for `CommandConfiguration`. Since the new property has a default value, most existing source should not be affected. Source that references the old initializer (instead of just calling it) will receive a deprecation warning.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Comment by natecook1000** [comment]
@swift-ci Please test

**Review by rauhul — APPROVED** [review]
Looks good to me! When I find some time I really want to refactor the help and usage generator into resultBuilders, I think it would make the string generation easier to follow and we could make swiftUI like modifiers for the indentation options.

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
